config/routes.rb
RailsBlog::Application.routes.draw do

  root 'posts#index'

  get 'signup' => 'users#new', :as => 'signup'
  get 'login' => 'sessions#new', :as => 'login'
  delete 'logout' => 'sessions#destroy', :as => 'logout'

  resources :sessions
  resources :users
  resources :tags
  
  resources :posts do 
    resources :comments, :only => [:new, :create, :edit, :destroy]
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :post

  validates_presence_of :content
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :comments, :dependent => :destroy
  has_many :post_tags
  has_many :tags, :through => :post_tags
  accepts_nested_attributes_for :tags, reject_if: lambda {|attributes| attributes['name'].blank?}
  validates_presence_of :name, :content
end

app/models/post_tag.rb
class PostTag < ActiveRecord::Base
  belongs_to :post
  belongs_to :tag
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :post_tags
  has_many :posts, :through => :post_tags

  validates_uniqueness_of :name
  validates_presence_of :name
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts
  has_many :comments

  validates_uniqueness_of :name
  validates_presence_of :name

  validates_uniqueness_of :email
  validates_presence_of :email

  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def user_signed_in?
    session[:user_id] ? true : false
  end
  helper_method :user_signed_in?

  private
    def current_user
      @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end
    helper_method :current_user

    def authorize
      render :new if !user_signed_in?
    end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authorize, only: [:new, :create, :edit, :update, :destroy]
  before_action :set_post, only: [:edit, :update, :destroy]

  def new
    @comment = Comment.new
  end

  def edit
  end

  def create
    @comment = Comment.new(comment_params)
    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment.post, notice: 'Comment was successfully created.' }
        format.json { render action: 'show', status: :created, location: @comment }
      else
        format.html { render action: 'new' }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment.post, notice: 'Comment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url }
      format.json { head :no_content }
    end
  end

  private
    def set_comment
      @comment = Comment.find(params[:id])
    end

    def comment_params
      params.require(:comment).permit(:content, :user_id, :post_id)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authorize, only: [:new, :create, :edit, :update, :destroy]
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  def index
    @posts = Post.all
  end

  def show
  end

  def new
    @post = Post.new
  end

  def edit
  end

  def create
    @post = Post.new(post_params)
    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render action: 'show', status: :created, location: @post }
      else
        format.html { render action: 'new' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end

  private
    def set_post
      @post = Post.find(params[:id])
    end

    def post_params
      params.require(:post).permit(:name, :content, :user_id, :tag_ids => [], :tags_attributes => [:id, :name], :comments_attributes => [:content, :user_id])
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
  end

  def create
    user = User.find_by(:email => params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url, :notice => "Welcome back, #{user.name}!"
    else
      flash.now.alert = "Invalid email or password"
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Logged out!"
  end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

  def index
    @tags = Tag.all
  end

  def show
    @tag = Tag.find(params[:id])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit]

  def index
    @users = User.all
  end

  def show
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_path, :notice => "Thank you for signing up!"
    else
      render :new
    end
  end

  private
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<nav>
  <ul>
      <li><%= link_to 'Posts', posts_path %></li>
      <% if current_user %>
        <li><a href="/users/<%=current_user.id%>"><%= "Hello, #{current_user.name}!" %></a></li>
        <li> <%= link_to 'New Post', new_post_path %> </li>
        <li><%= link_to "Log Out", logout_path, method: :delete %></li>
      <% else %>
        <li><%= link_to "Sign Up", signup_path %></li>
        <li><%= link_to "Log In", login_path %></li>
      <% end %> 
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsBlog</title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/header' %>
<%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %><br>
    <%= f.label :content %><br>
    <%= f.text_area :content %><br>
    <%= f.hidden_field :user_id, :value => session["user_id"] %>
    Tags:
  </div>

  <div class="field">
    <%= f.collection_check_boxes :tag_ids, Tag.all, :id, :name %><br>
    <%= f.fields_for(:tags, Tag.new) do |tag_form| %>
      <p>Add a new tag:</p><br>
      <%= tag_form.label :name %>
      <%= tag_form.text_field :name %>
    <% end %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/posts/_post.html.erb
<h2><%= link_to post.name, post %></h2> <span>written by: <%= post.user.name %> </span>

<% if !user_signed_in? %>
  <p> <%= link_to "Log in to Edit or Delete your Post", login_path %> </p>
<% else %>
  <p><%= link_to 'Edit', edit_post_path(post) %></p>
  <p><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></p>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>Blog Posts</h1>
<%= render @posts  %>


<br>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<h3>Title:</h3>
<%= @post.name %>
<h3>Content:</h3>
<%= @post.content %>
<h3>Posted by:</h3>
<%= @post.user.name %>
<h3>Tags:</h3>
<ul>
  <% @post.tags.each do |tag| %>
  <li><%= tag.name %></li>
  <% end %>
</ul>
<h3>Comments:</h3>
  <% @post.comments.each do |comment| %>
    <p><strong><%= comment.user.name %></strong> says ...</p> 
    <p><%= comment.content %> </p>
  <% end %>

<% if !user_signed_in? %>
  <%= link_to "Log In to Comment!", login_path %>
<% else %>
  <h4>Post a new comment:</h4>
  <%= form_for [@post, Comment.new] do |f| %>
    <div class="field">
      <%= f.label :content %><br>
      <%= f.text_area :content %><br>
      <%= f.hidden_field :post_id, :value => @post.id %>
      <%= f.hidden_field :user_id, :value => session["user_id"] %>
    </div>

    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>
<% end %>

<% if user_signed_in? %>
  <%= link_to 'Edit', edit_post_path(@post) %> |
<% end %>
<%= link_to 'Back', posts_path %>

app/views/tags/index.html.erb
<h1>Listing tags</h1>
  <ul>
    <% @tags.each do |tag| %>
        <li> <%= link_to tag.name, tag %> </li>
    <% end %>
  </ul>
<br>

<%= link_to 'New Tag', new_tag_path %>

app/views/tags/show.html.erb
<p id="notice"><%= notice %></p>

<p> <%= @tag.name %> </p>
<ul>
    <% @tag.posts.each do |post| %>
      <li> <%= link_to post.name, post_path(post) %> </li>
    <% end %>
</ul>

<%= link_to 'Back', tags_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %><br>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %><br>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %><br>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %><br>
  </div>
  <div class="actions">
    <%= f.submit "Sign Up" %>
  </div>
<% end %>

app/views/users/index.html.erb
<h1>Listing users</h1>

    <% @users.each do |user| %>
        <h2> <%= link_to user.name, user %> </h2>
    <% end %>
<br>
<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p> <%= @user.name %>  </p>

<%= link_to 'Back', users_path %>